import streamlit as st
import pandas as pd
import joblib

# -----------------------------
# Load trained model
# -----------------------------
model = joblib.load("student_score_model.pkl")


# -----------------------------
# Page configuration
# -----------------------------
st.set_page_config(
    page_title="Student Score Predictor",
    page_icon="🎓",
    layout="centered"
)


# -----------------------------
# Header
# -----------------------------
st.title("🎓 Student Score Predictor")

st.write(
    "Enter the student's academic and personal details "
    "to predict the expected exam score."
)

st.divider()


# -----------------------------
# Academic Information
# -----------------------------
st.subheader("📚 Academic Information")

col1, col2 = st.columns(2)

with col1:
    hours_studied = st.number_input(
        "Hours Studied",
        min_value=0,
        max_value=50,
        value=20
    )

    previous_scores = st.number_input(
        "Previous Scores",
        min_value=0,
        max_value=100,
        value=75
    )

    tutoring_sessions = st.number_input(
        "Tutoring Sessions",
        min_value=0,
        max_value=10,
        value=2
    )

with col2:
    attendance = st.number_input(
        "Attendance (%)",
        min_value=0,
        max_value=100,
        value=85
    )

    sleep_hours = st.number_input(
        "Sleep Hours",
        min_value=0,
        max_value=24,
        value=7
    )

    physical_activity = st.number_input(
        "Physical Activity (hours/week)",
        min_value=0,
        max_value=20,
        value=3
    )


# -----------------------------
# Student Information
# -----------------------------
st.subheader("👨‍🎓 Student Information")

col1, col2 = st.columns(2)

with col1:
    gender = st.selectbox(
        "Gender",
        ["Male", "Female"]
    )

    motivation_level = st.selectbox(
        "Motivation Level",
        ["Low", "Medium", "High"]
    )

    learning_disabilities = st.selectbox(
        "Learning Disabilities",
        ["No", "Yes"]
    )

with col2:
    internet_access = st.selectbox(
        "Internet Access",
        ["No", "Yes"]
    )

    extracurricular_activities = st.selectbox(
        "Extracurricular Activities",
        ["No", "Yes"]
    )

    peer_influence = st.selectbox(
        "Peer Influence",
        ["Negative", "Neutral", "Positive"]
    )


# -----------------------------
# Family and School Information
# -----------------------------
st.subheader("🏫 Family & School Information")

col1, col2 = st.columns(2)

with col1:
    parental_involvement = st.selectbox(
        "Parental Involvement",
        ["Low", "Medium", "High"]
    )

    parental_education_level = st.selectbox(
        "Parental Education Level",
        ["High School", "College", "Postgraduate"]
    )

    family_income = st.selectbox(
        "Family Income",
        ["Low", "Medium", "High"]
    )

with col2:
    access_to_resources = st.selectbox(
        "Access to Resources",
        ["Low", "Medium", "High"]
    )

    teacher_quality = st.selectbox(
        "Teacher Quality",
        ["Low", "Medium", "High"]
    )

    school_type = st.selectbox(
        "School Type",
        ["Public", "Private"]
    )


# -----------------------------
# Additional Information
# -----------------------------
st.subheader("📍 Additional Information")

distance_from_home = st.selectbox(
    "Distance from Home",
    ["Near", "Moderate", "Far"]
)


st.divider()


# -----------------------------
# Prediction
# -----------------------------
if st.button("🎯 Predict Exam Score", use_container_width=True):

    student_data = {
        "Hours_Studied": hours_studied,
        "Attendance": attendance,
        "Parental_Involvement": parental_involvement,
        "Access_to_Resources": access_to_resources,
        "Extracurricular_Activities": extracurricular_activities,
        "Sleep_Hours": sleep_hours,
        "Previous_Scores": previous_scores,
        "Motivation_Level": motivation_level,
        "Internet_Access": internet_access,
        "Tutoring_Sessions": tutoring_sessions,
        "Family_Income": family_income,
        "Teacher_Quality": teacher_quality,
        "School_Type": school_type,
        "Peer_Influence": peer_influence,
        "Physical_Activity": physical_activity,
        "Learning_Disabilities": learning_disabilities,
        "Parental_Education_Level": parental_education_level,
        "Distance_from_Home": distance_from_home,
        "Gender": gender
    }

    student_df = pd.DataFrame([student_data])

    # Feature engineering
    student_df["Study_Engagement"] = (
        student_df["Hours_Studied"]
        * student_df["Attendance"]
        / 100
    )

    # Make prediction
    prediction = model.predict(student_df)[0]

    st.success(
        f"🎓 Predicted Exam Score: {prediction:.2f}"
    )

    st.info(
        "This prediction is generated by the trained machine learning model."
    )